version: '3'

services:
  reverse-proxy:
    image: traefik:v2.11
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.http.address=:80
      - --entrypoints.mysql.address=:3306
      - --providers.docker.exposedbydefault=true
    ports:
      - "80:80"
      - "8080:8080"
      - "3306:3306"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: test_password
      MYSQL_DATABASE: course_catalog
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    volumes:
      - ./database/migrations:/docker-entrypoint-initdb.d
      - ./database/volume:/var/lib/mysql
    hostname: database.cc.localhost
    labels:
      - traefik.tcp.routers.mysql.entrypoints=mysql
      - traefik.tcp.routers.mysql.rule=HostSNI(`*`)
      - traefik.tcp.services.mysql.loadbalancer.server.port=3306
    ports:
      - 8001:3306

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    depends_on:
      - db
    volumes:
      - ./api/:/var/www/html/
      - /var/www/html/vendor/
      - /var/www/html/data/
    stdin_open: true
    tty: true
    hostname: api.cc.localhost
    extra_hosts:
      - "cc.localhost:host-gateway"
      - "api.cc.localhost:host-gateway"
    labels:
      - traefik.http.routers.api.rule=Host(`api.cc.localhost`)
      - "traefik.http.services.api.loadbalancer.server.port=80"
      # Optional: Traefik CORS middleware (handled by Slim, but here if you want)
      - traefik.http.middlewares.cors.headers.accesscontrolallowmethods=GET,POST,PUT,PATCH,DELETE,OPTIONS
      - traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=http://cc.localhost
      - traefik.http.middlewares.cors.headers.accesscontrolallowcredentials=true
      - traefik.http.routers.api.middlewares=cors

  front:
    image: php:8.3-apache
    container_name: front
    depends_on:
      - api
    volumes:
      - ./front_end/:/var/www/html/
    stdin_open: true
    tty: true
    hostname: cc.localhost
    extra_hosts:
      - "cc.localhost:host-gateway"
      - "api.cc.localhost:host-gateway"
    labels:
      - traefik.http.routers.front.rule=Host(`cc.localhost`)